name: auto-merge

on:
  pull_request:
  pull_request_target:
    branches:
      - main
    types:
      - opened

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.dependabot || github.token }}
permissions:
  contents: read
  pull-requests: write
